package studio.kdb.config;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import studio.core.Credentials;
import studio.core.DefaultAuthenticationMechanism;
import studio.kdb.Config;
import studio.kdb.Server;
import studio.kdb.ServerTreeNode;
import studio.utils.FileConfig;
import studio.utils.MockConfig;
import studio.utils.QConnection;

import java.awt.*;
import java.io.File;
import java.io.IOException;

import static org.junit.jupiter.api.Assertions.*;


// Auto-generated by Copilot test suite for ServerConfig.lookup method (all 4 overloaded versions).
// I haven't reviewed them.

/**
 * Comprehensive test suite for ServerConfig.lookup method (all 4 overloaded versions).
 * Tests cover exact matches, multiple matches with weighting, filtering constraints,
 * no-match fallback behavior, auth mechanisms, TLS/protocol handling, and edge cases.
 */
public class ServerConfigLookupTest {

    private ServerConfig serverConfig;
    private File configFile;

    // Test fixtures
    private Server serverA;  // host1:5001, user1:pwd1, TLS=true, auth=DefaultAuth
    private Server serverB;  // host1:5001, user2:pwd2, TLS=true, auth=custom
    private Server serverC;  // host1:5001, user1:pwd1, TLS=false, auth=DefaultAuth
    private Server serverD;  // host2:5002, user1:pwd1, TLS=true, auth=DefaultAuth
    private Server serverE;  // host3:5003, no user/pwd, TLS=true, auth=custom

    @BeforeEach
    public void setUp() throws IOException {
        MockConfig.mock();
        Config.getInstance().setDefaultAuthMechanism(DefaultAuthenticationMechanism.NAME);
        Config.getInstance().setBoolean(Config.TRY_TLS_CONNECTION_FIRST, true);
        Config.getInstance().setBoolean(Config.FAILOVER_BETWEEN_TLS_AND_TCP_CONNECTIONS, false);

        configFile = File.createTempFile("serverConfigLookup", "json");
        configFile.delete();
        serverConfig = new ServerConfig(new FileConfig(configFile.toPath()));

        // Create test fixtures
        Color testColor = new Color(100, 150, 200);
        serverA = new Server("serverA", "host1", 5001, "user1", "pwd1", testColor, DefaultAuthenticationMechanism.NAME, true);
        serverB = new Server("serverB", "host1", 5001, "user2", "pwd2", testColor, "customAuth", true);
        serverC = new Server("serverC", "host1", 5001, "user1", "pwd1", testColor, DefaultAuthenticationMechanism.NAME, false);
        serverD = new Server("serverD", "host2", 5002, "user1", "pwd1", testColor, DefaultAuthenticationMechanism.NAME, true);
        serverE = new Server("serverE", "host3", 5003, "", "", testColor, "customAuth", true);
    }

    // ======================= EXACT MATCH TESTS =======================

    @Test
    public void testExactMatchSingleServer() {
        serverConfig.addServer(serverA);
        QConnection conn = new QConnection("host1", 5001, "user1", "pwd1", true);
        Server result = serverConfig.lookup(conn, DefaultAuthenticationMechanism.NAME);
        assertEquals("serverA", result.getName());
        assertEquals("host1", result.getHost());
        assertEquals(5001, result.getPort());
    }

    @Test
    public void testExactMatchWithExplicitUser() {
        serverConfig.addServer(serverA);
        QConnection conn = new QConnection("host1", 5001, "user1", "", true);
        Server result = serverConfig.lookup(conn, DefaultAuthenticationMechanism.NAME);
        assertEquals("serverA", result.getName());
        assertEquals("user1", result.getUsername());
    }

    @Test
    public void testExactMatchWithExplicitPassword() {
        serverConfig.addServer(serverA);
        QConnection conn = new QConnection("host1", 5001, "", "pwd1", true);
        Server result = serverConfig.lookup(conn, DefaultAuthenticationMechanism.NAME);
        assertEquals("serverA", result.getName());
        assertEquals("pwd1", result.getPassword());
    }

    @Test
    public void testExactMatchWithExplicitProtocol() {
        serverConfig.addServer(serverA);
        serverConfig.addServer(serverC);
        QConnection conn = new QConnection("host1", 5001, "user1", "pwd1", true);
        Server result = serverConfig.lookup(conn, DefaultAuthenticationMechanism.NAME);
        // Should prefer serverA (TLS=true) over serverC (TLS=false)
        assertEquals("serverA", result.getName());
        assertTrue(result.getUseTLS());
    }

    // ======================= MULTIPLE MATCH TESTS =======================

    @Test
    public void testMultipleMatchWeightByDefaultAuthMechanism() {
        serverConfig.addServer(serverA);  // DefaultAuth + TLS=true
        serverConfig.addServer(serverB);  // customAuth + TLS=true
        QConnection conn = new QConnection("host1", 5001, "", "", true);
        Server result = serverConfig.lookup(conn, null);
        // serverA should win: weight=3 (auth=2 + TLS=1) vs serverB weight=1 (TLS=1)
        assertEquals("serverA", result.getName());
    }

    @Test
    public void testMultipleMatchWeightByTLSDefault() {
        Config.getInstance().setBoolean(Config.TRY_TLS_CONNECTION_FIRST, true);
        serverConfig.addServer(serverA);  // TLS=true
        serverConfig.addServer(serverC);  // TLS=false
        // Use connection string with explicit protocol to set specifiedProtocol flag
        Server result = serverConfig.lookup("`:tcp://host1:5001:user1:pwd1", DefaultAuthenticationMechanism.NAME);
        // serverC should win: TLS explicitly specified as false (tcp), matches serverC
        assertEquals("serverC", result.getName());
    }

    @Test
    public void testMultipleMatchCombinedAuthAndTLSWeight() {
        serverConfig.addServer(serverA);  // DefaultAuth=true, TLS=true (weight=3)
        serverConfig.addServer(serverB);  // CustomAuth, TLS=true (weight=1)
        serverConfig.addServer(serverC);  // DefaultAuth=true, TLS=false (weight=2)
        QConnection conn = new QConnection("host1", 5001, "", "", true);
        Server result = serverConfig.lookup(conn, null);
        // serverA has highest weight (3)
        assertEquals("serverA", result.getName());
    }

    @Test
    public void testMultipleMatchEqualWeightReturnsFirst() {
        serverConfig.addServer(serverB);  // customAuth, TLS=true
        serverConfig.addServer(serverE);  // customAuth, TLS=true
        QConnection conn = new QConnection("host3", 5003, "", "", true);
        Server result = serverConfig.lookup(conn, "customAuth");
        // Both have weight=0 (no auth bonus, but TLS not default when no default set)
        // Should return first one added (serverE)
        assertEquals("serverE", result.getName());
    }

    // ======================= FILTER CONSTRAINT TESTS =======================
    // NOTE: Constraint filtering only works with connection strings (which set the "specified" flags)
    // When using QConnection directly, the Parser doesn't know what was "specified"

    @Test
    public void testFilterUserSpecifiedConstraint() {
        serverConfig.addServer(serverA);  // user1
        serverConfig.addServer(serverB);  // user2
        // Use connection string to set specifiedUser flag
        Server result = serverConfig.lookup("`:host1:5001:user2", DefaultAuthenticationMechanism.NAME);
        // Should not match serverA (user mismatch)
        // serverB has wrong auth, so fallback
        assertTrue(result.getName().isEmpty());
    }

    @Test
    public void testFilterPasswordSpecifiedConstraint() {
        serverConfig.addServer(serverA);  // pwd1
        serverConfig.addServer(serverB);  // pwd2
        // Use connection string to set specifiedPassword flag
        Server result = serverConfig.lookup("`:host1:5001:user:pwd2", DefaultAuthenticationMechanism.NAME);
        // Should not match serverA (password mismatch)
        // serverB has wrong auth, so fallback
        assertTrue(result.getName().isEmpty());
    }

    @Test
    public void testFilterProtocolSpecifiedConstraint() {
        serverConfig.addServer(serverA);  // TLS=true
        serverConfig.addServer(serverC);  // TLS=false
        // Use connection string to set specifiedProtocol flag
        Server result = serverConfig.lookup("`:tcp://host1:5001", DefaultAuthenticationMechanism.NAME);
        // Should match serverC (TLS=false) based on protocol constraint
        assertEquals("serverC", result.getName());
    }

    @Test
    public void testFilterAllConstraintsTogether() {
        serverConfig.addServer(serverA);  // user1, pwd1, TLS=true
        serverConfig.addServer(serverB);  // user2, pwd2, TLS=true
        serverConfig.addServer(serverC);  // user1, pwd1, TLS=false
        // Connection string sets all constraints
        Server result = serverConfig.lookup("`:tcp://host1:5001:user1:pwd1", DefaultAuthenticationMechanism.NAME);
        // Should match serverC (all constraints match)
        assertEquals("serverC", result.getName());
    }

    // ======================= NO MATCH TESTS =======================

    @Test
    public void testNoMatchEmptyConfig() {
        QConnection conn = new QConnection("host1", 5001, "", "", true);
        Server result = serverConfig.lookup(conn, DefaultAuthenticationMechanism.NAME);
        // Should create fallback server
        assertEquals("host1", result.getHost());
        assertEquals(5001, result.getPort());
        assertTrue(result.getName().isEmpty());
        assertEquals(DefaultAuthenticationMechanism.NAME, result.getAuthenticationMechanism());
    }

    @Test
    public void testNoMatchNoHostPortMatch() {
        serverConfig.addServer(serverA);  // host1:5001
        QConnection conn = new QConnection("host999", 9999, "", "", true);
        Server result = serverConfig.lookup(conn, DefaultAuthenticationMechanism.NAME);
        // No server matches host999:9999, create fallback
        assertEquals("host999", result.getHost());
        assertEquals(9999, result.getPort());
    }

    @Test
    public void testNoMatchConstraintsEliminateAll() {
        serverConfig.addServer(serverA);  // user1, TLS=true
        // Use connection string with different user to enforce constraint
        Server result = serverConfig.lookup("`:host1:5001:user2", DefaultAuthenticationMechanism.NAME);
        // serverA doesn't match user2 constraint, create fallback
        assertTrue(result.getName().isEmpty());
        assertEquals("host1", result.getHost());
    }

    @Test
    public void testNoMatchCreateFallbackWithDefaults() {
        Config.getInstance().setBoolean(Config.TRY_TLS_CONNECTION_FIRST, false);
        Config.getInstance().setBoolean(Config.FAILOVER_BETWEEN_TLS_AND_TCP_CONNECTIONS, true);
        QConnection conn = new QConnection("testhost", 1234, "", "", false);
        Server result = serverConfig.lookup(conn, "testAuth");
        assertEquals("testhost", result.getHost());
        assertEquals(1234, result.getPort());
        assertEquals("testAuth", result.getAuthenticationMechanism());
        assertFalse(result.getUseTLS());
        assertTrue(result.isFlipTLS());
    }

    // ======================= AUTH MECHANISM TESTS =======================

    @Test
    public void testAuthExplicitProvided() {
        serverConfig.addServer(serverB);  // customAuth
        QConnection conn = new QConnection("host1", 5001, "user2", "pwd2", true);
        Server result = serverConfig.lookup(conn, "customAuth");
        assertEquals("serverB", result.getName());
        assertEquals("customAuth", result.getAuthenticationMechanism());
    }

    @Test
    public void testAuthNullUsesConfigDefault() {
        serverConfig.addServer(serverA);  // DefaultAuth
        QConnection conn = new QConnection("host1", 5001, "user1", "pwd1", true);
        Server result = serverConfig.lookup(conn, null);
        // auth=null, should use Config default (DefaultAuthenticationMechanism.NAME)
        assertEquals("serverA", result.getName());
    }

    @Test
    public void testAuthMatchesConfigDefaultGetsWeight() {
        serverConfig.addServer(serverA);  // DefaultAuth (weight bonus)
        serverConfig.addServer(serverB);  // customAuth (no weight bonus)
        QConnection conn = new QConnection("host1", 5001, "", "", true);
        Server result = serverConfig.lookup(conn, null);
        // Should prefer serverA due to default auth match (weight=3 vs 1)
        assertEquals("serverA", result.getName());
    }

    @Test
    public void testAuthNonDefault() {
        serverConfig.addServer(serverB);  // customAuth
        QConnection conn = new QConnection("host1", 5001, "user2", "pwd2", true);
        Server result = serverConfig.lookup(conn, "customAuth");
        assertEquals("serverB", result.getName());
    }

    @Test
    public void testAuthWithDefaultCredentials() throws IOException {
        Config.getInstance().setDefaultCredentials("customAuth", new Credentials("defaultUser", "defaultPwd"));
        QConnection conn = new QConnection("host3", 5003, "", "", true);
        Server result = serverConfig.lookup(conn, "customAuth");
        // No server found, fallback should use default credentials
        assertEquals("host3", result.getHost());
        assertEquals("defaultUser", result.getUsername());
        assertEquals("defaultPwd", result.getPassword());
    }

    // ======================= TLS/PROTOCOL TESTS =======================

    @Test
    public void testTLSEnabledInParser() {
        serverConfig.addServer(serverA);  // TLS=true
        QConnection conn = new QConnection("host1", 5001, "user1", "pwd1", true);
        Server result = serverConfig.lookup(conn, DefaultAuthenticationMechanism.NAME);
        assertEquals("serverA", result.getName());
        assertTrue(result.getUseTLS());
    }

    @Test
    public void testTLSDisabledInParser() {
        serverConfig.addServer(serverC);  // TLS=false
        QConnection conn = new QConnection("host1", 5001, "user1", "pwd1", false);
        Server result = serverConfig.lookup(conn, DefaultAuthenticationMechanism.NAME);
        assertEquals("serverC", result.getName());
        assertFalse(result.getUseTLS());
    }

    @Test
    public void testTLSNotSpecifiedUsesDefault() {
        Config.getInstance().setBoolean(Config.TRY_TLS_CONNECTION_FIRST, true);
        QConnection conn = new QConnection("host1", 5001, "", "", false);
        Server result = serverConfig.lookup(conn, DefaultAuthenticationMechanism.NAME);
        // TLS=false in connection, no servers match, fallback uses config default (true)
        assertTrue(result.getUseTLS());
    }

    @Test
    public void testTLSWeightCalculation() {
        Config.getInstance().setBoolean(Config.TRY_TLS_CONNECTION_FIRST, true);
        serverConfig.addServer(serverA);  // TLS=true (matches default, weight +1)
        serverConfig.addServer(serverC);  // TLS=false (doesn't match default)
        QConnection conn = new QConnection("host1", 5001, "user1", "pwd1", true);
        Server result = serverConfig.lookup(conn, DefaultAuthenticationMechanism.NAME);
        // Both match, but serverA should win due to TLS weight
        assertEquals("serverA", result.getName());
    }

    @Test
    public void testTLSFlipEnabledInConfig() {
        Config.getInstance().setBoolean(Config.FAILOVER_BETWEEN_TLS_AND_TCP_CONNECTIONS, true);
        QConnection conn = new QConnection("host999", 9999, "", "", false);
        Server result = serverConfig.lookup(conn, "testAuth");
        // Fallback server should have flipTLS enabled
        assertTrue(result.isFlipTLS());
    }

    // ======================= CREDENTIAL HANDLING TESTS =======================

    @Test
    public void testCredentialUserSpecifiedInParser() {
        serverConfig.addServer(serverA);  // user1, pwd1
        QConnection conn = new QConnection("host1", 5001, "user1", "", true);
        Server result = serverConfig.lookup(conn, DefaultAuthenticationMechanism.NAME);
        assertEquals("serverA", result.getName());
        assertEquals("user1", result.getUsername());
    }

    @Test
    public void testCredentialPasswordSpecifiedInParser() {
        serverConfig.addServer(serverA);  // user1, pwd1
        QConnection conn = new QConnection("host1", 5001, "", "pwd1", true);
        Server result = serverConfig.lookup(conn, DefaultAuthenticationMechanism.NAME);
        assertEquals("serverA", result.getName());
        assertEquals("pwd1", result.getPassword());
    }

    @Test
    public void testCredentialNeitherSpecifiedUsesDefaults() throws IOException {
        Config.getInstance().setDefaultCredentials(DefaultAuthenticationMechanism.NAME, new Credentials("defaultUser", "defaultPwd"));
        QConnection conn = new QConnection("host999", 9999, "", "", true);
        Server result = serverConfig.lookup(conn, DefaultAuthenticationMechanism.NAME);
        // No server found, fallback uses default credentials
        assertEquals("defaultUser", result.getUsername());
        assertEquals("defaultPwd", result.getPassword());
    }

    // ======================= OVERLOADED METHODS TESTS =======================

    @Test
    public void testMethodQConnectionWithAuth() {
        serverConfig.addServer(serverA);
        QConnection conn = new QConnection("host1", 5001, "user1", "pwd1", true);
        Server result = serverConfig.lookup(conn, DefaultAuthenticationMechanism.NAME);
        assertEquals("serverA", result.getName());
    }

    @Test
    public void testMethodConnectionStringOnly() {
        serverConfig.addServer(serverA);
        Server result = serverConfig.lookup("`:host1:5001:user1:pwd1");
        assertEquals("serverA", result.getName());
    }

    @Test
    public void testMethodConnectionStringWithAuth() {
        serverConfig.addServer(serverA);
        Server result = serverConfig.lookup("`:host1:5001:user1:pwd1", DefaultAuthenticationMechanism.NAME);
        assertEquals("serverA", result.getName());
    }

    @Test
    public void testMethodQConnectionParserWithAuth() {
        serverConfig.addServer(serverA);
        QConnection.Parser parser = new QConnection.Parser(new QConnection("host1", 5001, "user1", "pwd1", true));
        Server result = serverConfig.lookup(parser, DefaultAuthenticationMechanism.NAME);
        assertEquals("serverA", result.getName());
    }

    // ======================= EDGE CASES =======================

    @Test
    public void testEdgeInvalidParserErrorHandling() {
        // Parser with errors should return NO_SERVER
        Server result = serverConfig.lookup("invalid:connection:string", DefaultAuthenticationMechanism.NAME);
        // Parser.hasError() will return true, lookup returns Server.NO_SERVER
        assertEquals(Server.NO_SERVER, result);
    }

    @Test
    public void testEdgeNullAuthWithSpecifiedUser() {
        serverConfig.addServer(serverA);  // DefaultAuth
        // With specified user and null auth, should default to DefaultAuthenticationMechanism
        Server result = serverConfig.lookup("`:host1:5001:user1", null);
        assertEquals("serverA", result.getName());
    }

    @Test
    public void testEdgeConnectionStringParsing() {
        serverConfig.addServer(serverA);
        // Test with standard q connection string format (tcps for TLS)
        Server result = serverConfig.lookup("`:tcps://host1:5001:user1:pwd1");
        assertEquals("serverA", result.getName());
    }

    @Test
    public void testEdgeMissingServerInFolderPath() {
        ServerTreeNode folder = new ServerTreeNode("testFolder");
        serverConfig.getServerTree().add(folder);
        // Verify no error when looking up a connection
        assertDoesNotThrow(() -> {
            serverConfig.lookup("`:host1:5001", DefaultAuthenticationMechanism.NAME);
        });
    }

}
