name: Build distribution package

on:
  push:
    branches: [ 'build_distro' ]
jobs:
  WindowDistribution:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - run: gradlew.bat build
      - uses: dorny/test-reporter@v1
        if: always()
        with:
          name: JUnit Tests
          path: build/test-results/*/*.xml
          reporter: java-junit
          fail-on-error: true
