# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  # Specify OS for the matrix

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 9
      uses: actions/setup-java@v2
      with:
        java-version: '9'
        distribution: 'zulu'
        cache: gradle

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build with Gradle
      run: ./gradlew build
      timeout-minutes: 2

    - name: Integration tests - Linux
      if: ${{ runner.os == 'Linux' }}
      run: ./intTests-Xvfb.sh
      timeout-minutes: 5

#    - name: Integration tests - Windows
#      if: ${{ runner.os == 'Windows' }}
#      run: ./gradlew integrationTest -x test
#      timeout-minutes: 5

    - name: Log files - Linux
      if: ${{ runner.os == 'Linux' }}
      run: find . -type f -exec echo {} \;

    - name: Log files - Linux
      if: ${{ runner.os == 'Windows' }}
      run: Get-ChildItem -Path . -Recurse -File

    - name: Upload Failed test screenshots
      uses: actions/upload-artifact@v3.1.2
      if: ${{ failure() }}
      with:
        name: Failed tests
        path: ./failed-gui-tests/

    - name: Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: JUnit Tests - ${{ runner.os }}
        path: build/test-results/*/*.xml
        reporter: java-junit
        fail-on-error: true

    - name: Upload reports in case of failure
      uses: actions/upload-artifact@v3.1.2
      if: ${{ failure() }}
      with:
        name: Failed Reports - ${{ runner.os }}
        path: ./build/reports/tests/

    - name: Upload Windows distribution
      if: ${{ runner.os == 'Windows' }}
      uses: actions/upload-artifact@v3.1.2
      with:
        name: Windows distribution
        path: build/distribution/kdbStudio.zip
